### ISSUE TITLE
Browserify's process.nextTick is always used.

### ISSUE THREAD

**Issue by anandthakker** [medikoo/next-tick#9]
Because browserify defines process.nextTick, this module always uses that implementation rather than the MutationObserver approach, even when the latter is supported in the browser.

I could see an argument that this is the right way to go here, but I'm 100% sure.  As of now, because I want to get better microtask scheduling, I am doing something like:

```js
process.nextTick = null
var nextTick = require('next-tick')
process.nextTick = nextTick
```

**Comment by medikoo** [comment]
Browserify's main goal is to bring Node.js API to browsers, so it's expected that it provides `process.nextTick`, and I'd say it's valid that `next-tick` (being in environment that pretends to be Node.js) fallbacks to `process.nextTick` that already exists.

I believe that issue here is that Browserify doesn't provide as efficient `nextTick` as it could. Have you tried to open the issue over there?

**Comment by anandthakker** [comment]
> Browserify's main goal is to bring Node.js API to browsers, so it's expected that it provides process.nextTick, and I'd say it's valid that next-tick (being in environment that pretends to be Node.js) fallbacks to process.nextTick that already exists

@medikoo Just curious: in what environment do you see next-tick's non-fallback implementation being used?  Not browserify and not node, right?

**Comment by medikoo** [comment]
> @medikoo Just curious: in what environment do you see next-tick's non-fallback implementation being used? Not browserify and not node, right?

Browser (Browserify is not an enviroment, but bundler you used, and it's just one of many, probably only one that tries to also bring Node.js API to browser)

**Comment by anandthakker** [comment]
> Browserify is not an enviroment, but bundler you used, and it's just one of many, probably only one that tries to also bring Node.js API to browser

It is both. The fact that browserify provides implementations for much of the Node API means that it affects the environment in which its users' code is run.

**Comment by medikoo** [comment]
> It is both. 

True, it can be seen that way. In last coment I was referring more to bare native implementation, probably _environment_ is not best word for that.

**Comment by mreinstein** [comment]
@anandthakker I ran into this issue too. If you're interested, I've published a nearly identical package which provides the same api but has _much_ smaller browserified bundles.

https://www.npmjs.com/package/next-tick-2

**Comment by medikoo** [comment]
@mreinstein good call. If I can suggest something, the name `next-tick-browserify` would play way better, it's [free to take](https://www.npmjs.com/package/next-tick-browserify) and it will improve discoverability of it for other browserify users which may approach very same problem.

**Comment by mreinstein** [comment]
@medikoo 

>  the name next-tick-browserify would play way better

The problem with that is the name would incorrectly imply the module is only specific to browserify. `next-tick-2` is 100% compatible with `next-tick`, has the same features, but _also_ has much smaller results when bundled via browserify.

**Comment by medikoo** [comment]
> The problem with that is the name would incorrectly imply the module is only specific to browserify.

It was created purely as a workaround to issue you had when using it with browserify, you would not see a need for it otherwise :)

**Comment by mreinstein** [comment]
> It was created purely as a workaround to issue you had when using it with browserify

True, but browserify is most popular bundling strategy in node/npm these days. It is a workaround that applies to a large number of `next-tick` 's users.

**Comment by medikoo** [comment]
> It is a workaround that applies to a large number of next-tick 's users.

Still, purely *browserify* users. That's why I suggested that you may make this package more discoverable for exactly those users (as you noticed, it's a large group), they will be thankful

**Comment by mreinstein** [comment]
> Still, purely browserify users

Putting `browserify` in the module name implies the module only works for browserify, which is not accurate.

The module works the exact same way as yours. The only difference is if you happen to be using browserify you get smaller bundles. There is no need to do anything special or use a certain module. Just use `next-tick-2` everywhere instead, and regardless of whatever bundling strategy you use, it will give equal or smaller results than `next-tick`.
